apiVersion: v1
kind: Service
metadata:
  name: posts-service
spec:
  type: LoadBalancer
  selector:
    app: posts-service
  ports:
    - name: grpc
      protocol: TCP
      port: 50052
      targetPort: 50052
  type: ClusterIP
